name: Reproduce Python 3.14.0rc1 asyncio introspection feature
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Attemp to reproduce, non-reproduction of Python 3.14.0rc1 asyncio introspection feature
    
    strategy: 
      fail-fast: false
      matrix:
        os: [
          "macos-latest",
          "ubuntu-24.04",
          "windows-latest",
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    # - name: Create Python 3.14.0rc1 venv
    #   run: uv venv .venv --python=3.14.0rc1

    # - name: Run example app
    #   shell: bash
    #   run: |
    #     .venv/bin/python asyncio_example.py &
    #     echo "EXAMPLE_APP_PID=$!" >> $GITHUB_ENV

    - name: Install Python 3.14.0rc1
      run: uv python install 3.14.0rc1

    - name: Run example app
      shell: bash
      run: |
        uv run --python=3.14.0rc1 asyncio_example.py &
        echo "EXAMPLE_APP_PID=$!" >> $GITHUB_ENV

    - name: Run Asyncio introspection feature
      shell: bash
      run:
        uv run python -m asyncio ps ${{ env.EXAMPLE_APP_PID }}


    - name: Stop example app
      shell: bash
      run: |
        echo Killing process ID: ${{ env.EXAMPLE_APP_PID }}
        kill ${{ env.EXAMPLE_APP_PID }}
  
