name: Reproduce Python 3.14.0rc1 asyncio introspection feature
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Attemp to reproduce, non-reproduction of Python 3.14.0rc1 asyncio introspection feature
    
    strategy: 
      matrix:
        os: [
          "macos-latest",
          "ubuntu-24.04",
          "windows-latest",
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Create Python 3.14.0rc1 venv
      run: uv venv .venv --python=3.14.0rc1

    - name: Run example app
      run: |
        .venv/bin/python asyncio_example.py &
        echo "EXAMPLE_APP_PID=$!" >> $GITHUB_ENV



    - name: Stop example app
      run: |
        echo Killing process ID: ${{ env.EXAMPLE_APP_PID }}
        kill ${{ env.HTTP_SERVER_PID }}
  
