name: Reproduce Python 3.14.0rc1 asyncio introspection feature
on:
  push:
  workflow_dispatch:
jobs:

  test:
    name: Attemp to reproduce, non-reproduction of Python 3.14.0rc1 asyncio introspection feature

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Create Python 3.14.0rc1 venv
      run: uv venv .venv --python=3.14.0rc1
